### ISSUE TITLE
TextInputEditText

### ISSUE THREAD

**Issue by KungFooBar** [tinkoff-mobile-tech/decoro#22]
Если установить MaskFormatWatcher на TextInputEditText, то форматирование работает неправильно.

**Comment by busylee999** [comment]
Сказал, как отрезал!

**Comment by MaximKorobovAtTinkoff** [comment]
@Belousov2015Dmitry, разъясните или покажите gif-кой слово "неправильно".

**Comment by dmitrikudrenko** [comment]
В демо на экране "Готовая маска" заменил EditText на TextInputLayout. Никакой проблемы нет

**Comment by Wasylews** [comment]
Тоже столкнулся с такой проблемой.
![20190222_141241](https://user-images.githubusercontent.com/6310093/53242200-ba563f00-36ac-11e9-978b-7d8f0bfe50f9.gif)
Опытным путем выяснил, что такое происходит если указать значение inputType: number, numberSigned, numberDecimal. Даже если указать у простого EditText. При этом inputType phone работает без проблем.
